// Compliance certificate types with renewal frequencies

export const CERTIFICATE_TYPES = [
  {
    type: 'gas_safety' as const,
    label: 'Gas Safety Certificate',
    description: 'Annual gas safety inspection by a Gas Safe registered engineer.',
    frequency: 'Annual',
    frequencyMonths: 12,
    required: true,
    legislation: 'Gas Safety (Installation and Use) Regulations 1998',
    fine: 'Up to £6,000 or 6 months imprisonment',
  },
  {
    type: 'eicr' as const,
    label: 'Electrical Installation Condition Report (EICR)',
    description: 'Inspection of the electrical installation by a qualified electrician.',
    frequency: 'Every 5 years',
    frequencyMonths: 60,
    required: true,
    legislation: 'Electrical Safety Standards in the Private Rented Sector (England) Regulations 2020',
    fine: 'Up to £30,000',
  },
  {
    type: 'epc' as const,
    label: 'Energy Performance Certificate (EPC)',
    description: 'Assessment of the energy efficiency of the property.',
    frequency: 'Every 10 years',
    frequencyMonths: 120,
    required: true,
    legislation: 'Energy Performance of Buildings (England and Wales) Regulations 2012',
    fine: 'Up to £5,000',
  },
  {
    type: 'smoke_co' as const,
    label: 'Smoke & CO Alarm Compliance',
    description: 'Smoke alarms on every floor, CO alarms in rooms with solid fuel appliances. Must test at start of each tenancy.',
    frequency: 'Test at each new tenancy',
    frequencyMonths: 12,
    required: true,
    legislation: 'Smoke and Carbon Monoxide Alarm (Amendment) Regulations 2022',
    fine: 'Up to £5,000',
  },
  {
    type: 'legionella' as const,
    label: 'Legionella Risk Assessment',
    description: 'Assessment of the risk of Legionella bacteria in the water system.',
    frequency: 'Every 2 years (recommended)',
    frequencyMonths: 24,
    required: false,
    legislation: 'Health and Safety at Work Act 1974 (duty of care)',
    fine: 'Varies — civil liability',
  },
  {
    type: 'buildings_insurance' as const,
    label: 'Buildings Insurance',
    description: 'Insurance covering the structure of the property.',
    frequency: 'Annual',
    frequencyMonths: 12,
    required: false,
    legislation: 'Usually required by mortgage lender',
    fine: 'N/A — contractual obligation',
  },
  {
    type: 'landlord_insurance' as const,
    label: 'Landlord Insurance',
    description: 'Specialist landlord insurance covering rental property risks.',
    frequency: 'Annual',
    frequencyMonths: 12,
    required: false,
    legislation: 'Recommended but not legally required',
    fine: 'N/A — risk to landlord',
  },
  {
    type: 'hmo_licence' as const,
    label: 'HMO Licence',
    description: 'Licence required for Houses in Multiple Occupation (3+ tenants from 2+ households).',
    frequency: 'Every 5 years',
    frequencyMonths: 60,
    required: false,
    legislation: 'Housing Act 2004',
    fine: 'Unlimited fine plus rent repayment order',
  },
  {
    type: 'right_to_rent' as const,
    label: 'Right to Rent Check',
    description: 'Check that all adult tenants have the right to rent in England.',
    frequency: 'At start of tenancy + follow-up checks',
    frequencyMonths: 12,
    required: true,
    legislation: 'Immigration Act 2014',
    fine: 'Up to £3,000 per tenant (civil) or 5 years imprisonment (criminal)',
  },
] as const;

export type CertType = typeof CERTIFICATE_TYPES[number]['type'];
